services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - backend
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=DEBUG
    ports:
      - 16686:16686 # the jaeger UI port
      - 9411:9411 # Zipkin compatible http port for sending traces
      - 4317:4317 # the open telemetry grpc port for sending traces
      - 4318:4318 # the open telemetry http port for sending traces
networks:
  backend: