server:
  port: 8084

spring:
  application:
    name: visits-service

management:
  server:
    port: 9101
  health:
    probes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  otlp:
    tracing:
      enabled: false
      endpoint: http://localhost:4318/v1/traces
    metrics:
      enabled: false
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
  tracing:
    sampling:
      probability: 1.0

otel:
  logs:
    exporter:
      enabled: false
    endpoint: http://localhost:3100/loki/api/v1/push

spring:
  datasource:
    initialization-mode: always
    schema: classpath*:db/hsqldb/schema.sql
    data: classpath*:db/hsqldb/data.sql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  zipkin:
    enabled: false
---
spring:
  profiles: mysql
  datasource:
    schema: classpath*:db/mysql/schema.sql
    data: classpath*:db/mysql/data.sql

logging.level:
  org.springframework: DEBUG
  org.springframework.jdbc.core: TRACE
  io.micrometer.observation: TRACE